import { Conversation } from '../types';

/**
 * Sanitizes a string to make it safe for filenames across operating systems.
 */
export function sanitizeFilename(title: string): string {
  const clean = title
    .replace(/[\\/:*?"<>|]/g, '')
    .replace(/\s+/g, '_')
    .trim()
    .slice(0, 50);
  return clean || 'thinkpulse_conversation';
}

/**
 * Initiates a browser client-side download for text-based files (JSON, Markdown, etc.).
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Exports a conversation as a structured, formatted JSON document.
 */
export function exportConversationAsJSON(conversation: Conversation): string {
  const exportPayload = {
    appName: 'ThinkPulse AI',
    exportVersion: '1.0',
    exportedAt: new Date().toISOString(),
    conversation: {
      id: conversation.id,
      title: conversation.title,
      model: conversation.model || 'gemini-3.8-flash',
      updatedAt: conversation.updatedAt,
      messageCount: conversation.messages.length,
      messages: conversation.messages.map((m) => ({
        id: m.id,
        role: m.role,
        content: m.content,
        timestamp: m.timestamp,
        modelUsed: m.modelUsed,
        thinkingProcess: m.thinkingProcess,
        attachments: m.attachments
          ? m.attachments.map((att) => ({
              name: att.name,
              type: att.type,
              size: att.size,
            }))
          : undefined,
      })),
    },
  };

  const jsonContent = JSON.stringify(exportPayload, null, 2);
  const filename = `${sanitizeFilename(conversation.title)}.json`;
  downloadFile(jsonContent, filename, 'application/json');
  return filename;
}

/**
 * Exports a conversation as a beautifully formatted, GitHub/Notion/Obsidian-compatible Markdown document.
 */
export function exportConversationAsMarkdown(conversation: Conversation): string {
  const dateStr = new Date().toLocaleString([], {
    dateStyle: 'full',
    timeStyle: 'medium',
  });

  const lines: string[] = [
    `# ${conversation.title || 'Untitled Conversation'}`,
    '',
    `> **Platform:** ThinkPulse AI (ChatGPT Compatible Architecture)  `,
    `> **Exported Date:** ${dateStr}  `,
    `> **Default Model:** ${conversation.model || 'ThinkPulse 4o'}  `,
    `> **Total Messages:** ${conversation.messages.length}  `,
    '',
    '---',
    '',
  ];

  if (conversation.messages.length === 0) {
    lines.push('*This conversation contains no messages.*');
  } else {
    conversation.messages.forEach((msg, idx) => {
      const msgTime = new Date(msg.timestamp).toLocaleString([], {
        dateStyle: 'medium',
        timeStyle: 'short',
      });

      if (msg.role === 'user') {
        lines.push(`### 🧑 User`);
        lines.push(`*Sent: ${msgTime}*`);
        lines.push('');

        if (msg.attachments && msg.attachments.length > 0) {
          lines.push(
            `> 📎 **Attachments:** ${msg.attachments.map((a) => `\`${a.name}\``).join(', ')}`
          );
          lines.push('');
        }

        lines.push(msg.content);
        lines.push('');
        lines.push('---');
        lines.push('');
      } else {
        const modelLabel = msg.modelUsed || conversation.model || 'ThinkPulse 4o';
        lines.push(`### 🤖 ThinkPulse AI (${modelLabel})`);
        lines.push(`*Generated: ${msgTime}*`);
        lines.push('');

        if (msg.thinkingProcess) {
          lines.push('<details>');
          lines.push('<summary><strong>🧠 Step-by-Step Reasoning / Thought Process</strong></summary>');
          lines.push('');
          lines.push(`> ${msg.thinkingProcess.replace(/\n/g, '\n> ')}`);
          lines.push('</details>');
          lines.push('');
        }

        lines.push(msg.content);
        lines.push('');
        lines.push('---');
        lines.push('');
      }
    });
  }

  lines.push('');
  lines.push(`*Generated by ThinkPulse AI. Offline record created on ${dateStr}.*`);

  const mdContent = lines.join('\n');
  const filename = `${sanitizeFilename(conversation.title)}.md`;
  downloadFile(mdContent, filename, 'text/markdown');
  return filename;
}
